<a href="https://colab.research.google.com/github/kabir5145/Pytorch-Learning/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

  Introduction to Tensors
  
  Creating tensors

In [ ]:
# Scalar
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [ ]:
scalar.ndim

0

In [ ]:
# Get back the python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7, 7])
1
torch.Size([2])


In [ ]:
# Matrix
Matrix = torch.tensor([[1,2,3],
                       [4,5,6]])
Matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
print(Matrix.ndim)
print(Matrix.shape)

2
torch.Size([2, 3])


In [ ]:
Matrix[0]

tensor([1, 2, 3])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 3, 3])


In [45]:
TENSORs = torch.tensor([[1,2,3],
                       [4,4,4],
                       [3,3,3]])
print(TENSORs)

tensor([[1, 2, 3],
        [4, 4, 4],
        [3, 3, 3]])
