<a href="https://colab.research.google.com/github/kabir5145/Pytorch-Learning/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import torch
import numpy as np

  Introduction to Tensors
  
  Creating tensors

In [18]:
# Scalar
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [19]:
scalar.ndim

0

In [20]:
# Get back the python int
scalar.item()

7

In [21]:
# Vector
vector = torch.tensor([7,7])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7, 7])
1
torch.Size([2])


In [22]:
# Matrix
Matrix = torch.tensor([[1,2,3],
                       [4,5,6]])
Matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [23]:
print(Matrix.ndim)
print(Matrix.shape)

2
torch.Size([2, 3])


In [24]:
Matrix[0]

tensor([1, 2, 3])

In [25]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [26]:
print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 3, 3])


In [27]:
TENSORs = torch.tensor([[1,2,3],
                       [4,4,4],
                       [3,3,3]])
print(TENSORs)

tensor([[1, 2, 3],
        [4, 4, 4],
        [3, 3, 3]])


In [28]:
# Random tensors

random_tensor = torch.rand(4,4,4)
print(random_tensor)
print(random_tensor.ndim)

tensor([[[0.3614, 0.9845, 0.5658, 0.4896],
         [0.8148, 0.4864, 0.8596, 0.9531],
         [0.2626, 0.1515, 0.8477, 0.9309],
         [0.8628, 0.7675, 0.6169, 0.5403]],

        [[0.9075, 0.2829, 0.8236, 0.8385],
         [0.0983, 0.1998, 0.2638, 0.8255],
         [0.1509, 0.5563, 0.5555, 0.2788],
         [0.2836, 0.5828, 0.6623, 0.1671]],

        [[0.3684, 0.3333, 0.8645, 0.9123],
         [0.0182, 0.0240, 0.9929, 0.4938],
         [0.3592, 0.6137, 0.4326, 0.3267],
         [0.8380, 0.1333, 0.5803, 0.1671]],

        [[0.0776, 0.1899, 0.6035, 0.1957],
         [0.1350, 0.6274, 0.9042, 0.6159],
         [0.4499, 0.2204, 0.7645, 0.5366],
         [0.0427, 0.2196, 0.3160, 0.8510]]])
3


In [30]:
#create a random tenosor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (224,224,3)) # height , width , color channels(r,g,b)
random_image_size_tensor.ndim,random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))